; Hello World Assembly code for the 8086 microprocessor. The Intel 8086 is a 16-bit microprocessor introduced by Intel Corporation in 1978. The first x86 architecture chip
; Code written by Mushfiqur Rahman Abir
; Emulator used: emu8086

.MODEL SMALL ;SMALL, MEDIUM, LARGE ETC CAN BE USED
.STACK 100H ;SPECIFYING THE STACK SIZE
.DATA ;USED FOR DECLARING THE VARIABLES
CHAR DB "-"
MSG DB "HELLO WORLD$"
.CODE
MAIN PROC ;THE INT MAIN EQUIVALENT
    ;LOAD OR IMPORT THE DATA/VARIABLES
    MOV AX, @DATA
    MOV DS, AX ;MOVE THE ACCUMULATOR REGISTER DATA TO DATA SOURCE REGISTER SO THAT THE REST OF THE CODE CAN USE THEM
    
    MOV AH, 2 ;IT IS LIKE COUT IN C++ LANG, THE 2 HERE REPRESENTS FUNCTION CALL FOR PRINTING A CHAR ON THE SCREEN
    MOV DL, CHAR
    INT 21H ;CAUSED THE FUNCTION WHICH IS 2 TO BE EXECUTED AND PRINT WHATEVER IS IN THE DATA REGISTER
    
    MOV AH, 9 ;SO THAT STRINGS CAN BE LOADED INTO THE REGISTER
    LEA DX, MSG
    INT 21H
    
    ;RETURN THE CONTROL TO THE OPERATING SYSTEM. EQUIVALENT TO RETURN 0 IN C++
    MOV AH, 4CH
    INT 21H
    MAIN ENDP
END MAIN ; END THE MAIN PROC. SIMILAR TO THE EXIT(0) FUNCTION IN C++



    
    
    
